/* =============================================================================
   StreamStage booth kiosk — shared core
   Calgary Dance Teacher Expo, Tue Aug 11 – Wed Aug 12 2026

   THE ONE PLACE YOU EDIT.  Everything about the six products — the film file,
   the signup URL, the tile copy — lives in CONFIG below.

   What that does and does not cover, stated honestly rather than aspirationally:

     - The tablet tiles are built from CONFIG. Always were.
     - The TV's attract cards are hand-written HTML (tv.html) because each one
       carries bespoke copy CONFIG has never held. The two facts that ARE
       duplicated — the address line and, where marked, the tagline — are now
       overwritten from CONFIG at TV boot, so they cannot drift again. Anything
       else on those cards is genuinely only in tv.html.
     - The QR images are PRE-BAKED SVGs (qr/), generated by make-qr.py, which
       owns its own copy of the URLs and the ?src= tag. Changing a url here
       means re-running make-qr.py. Nothing in the browser builds a QR target.
     - serve.py derives its expected-film list by reading the ids below, so the
       server and this file cannot disagree about what should be on disk.

   Loaded by BOTH tablet.html and tv.html.  No dependencies, no network, no CDN.
   ========================================================================== */

var CONFIG = {

  /* ---------------------------------------------------------------------
     THE SIX PRODUCTS.  Order here == order of the tiles on the tablet.

     film[]  — tried in order, first one that loads wins.  Put the newest cut
               first.  sync-media.sh copies whichever exists upstream, so when
               Daniel's ElevenLabs VO lands and a new promo.mp4 is rendered,
               re-running sync-media.sh is the entire deploy.
     url     — the product's address.  Shown as text on both screens, and the
               destination make-qr.py bakes into qr/<surface>/<id>.svg with
               ?src=booth-calgary&p=<id>&s=<surface> appended — that tagged
               scan, counted on the destination side, is the ONLY true scan
               count we get.  CHANGE A URL HERE AND RE-RUN make-qr.py, or the
               printed address and the code under it stop agreeing.
     --------------------------------------------------------------------- */
  products: [
    {
      id:     'studiosage',
      name:   'StudioSage',
      short:  'The AI front desk. Parents text it.',
      tagline:'The AI front desk. Parents text it — it answers from your own emails.',
      film:   ['media/studiosage.mp4'],
      url:    'https://studiosage.ai'
    },
    {
      id:     'compsync',
      name:   'CompSync',
      short:  'Runs the whole competition weekend.',
      tagline:'Competition management, from entries through to the livestream.',
      film:   ['media/compsync.mp4'],
      // Confirmed by Daniel 2026-08-07.
      url:    'https://compsync.net'
    },
    {
      id:     'callboard',
      name:   'Callboard',
      short:  'Recital orders that know your rules.',
      tagline:'Recital running orders that already know your rules — siblings, quick changes, and the gaps in between.',
      film:   ['media/callboard.mp4'],
      url:    'https://callboard-scheduler.vercel.app'
    },
    {
      id:     'costumecraft',
      name:   'CostumeCraft',
      short:  'Design, measurements, quantities — one place.',
      tagline:'Design, measurements and per-class quantities in one place.',
      film:   ['media/costumecraft.mp4'],
      url:    'https://costume-craft.vercel.app'
    },
    {
      // The repo is called StudioSync. The PRODUCT is StudioBeat. "StudioSync"
      // is the old name and must never appear on a booth screen.
      id:     'studiobeat',
      name:   'StudioBeat',
      short:  'The whole studio, in one place.',
      tagline:'Classes, families, payments and the season calendar — one platform instead of five.',
      film:   ['media/studiobeat.mp4'],
      // Confirmed live 2026-08-06 (HTTP 200, Vercel, title "StudioBeat — Studio
      // Management"). Trailing slash is deliberate: without it the QR encodes
      // https://www.studiobeat.io?src=... — a query hung straight off the
      // authority, which is legal but not canonical. With it you get the
      // ordinary https://www.studiobeat.io/?src=... that every scanner expects.
      url:    'https://www.studiobeat.io/'
    },
    {
      id:     'reflect',
      name:   'Reflect',
      short:  'Every room on one screen.',
      // Verbatim from the film's own closing line, /mnt/data/reflect-video/out/
      // VO-SCRIPT.md beat 16.  NOT a tagline invented here, and NOT confirmed
      // by Daniel — see README-BOOTH.md.
      tagline:"The system that runs your studio's day — and remembers it.",
      film:   ['media/reflect.mp4'],
      url:    'https://reflect-vert.vercel.app/demo/login'
    }
  ],

  /* The community QR that is on BOTH screens at ALL times. Left clean on
     purpose: Facebook strips nothing, but Daniel has no way to read a query
     string off a group join, so an attribution tag would be a fake number. */
  facebook: {
    id:    'facebook',
    label: 'Join the community',
    sub:   'Studio owners + teachers. What ships next, first.',
    url:   'https://www.facebook.com/groups/2834366403591742'
  },

  /* Idle behaviour — the thing that matters more than the demo. */
  idle: {
    returnToAttractMs: 6000,   // after a film ends / is stopped, before attract
    tabletResetMs:     90000,  // tablet drops back to the tile grid if untouched
                               // — and the film gate re-arms for the next visitor
    tabletNowMs:       30000,  // Cap on the now-playing card, measured from the moment
                               // the card opened — but ONLY once the film has stopped.
                               // Daniel, 2026-08-13: "we want the qr scan on tablet to
                               // up as long as the video is playing". So while the TV is
                               // still playing this product the cap keeps deferring, and
                               // the product QR stays in front of the visitor for the
                               // whole film. It supersedes his earlier "only show that
                               // view for about 30 seconds" — that was written before the
                               // card carried a QR worth scanning.
                               // Unlike tabletResetMs it is NOT reset by touching the
                               // screen, so an idle tablet still cannot be parked on one
                               // product after the film ends.
                               // Deferred also while somebody is typing an email.
    visitorMemoryMs:  300000,  // HOW LONG THE GATE REMEMBERS A PERSON. Daniel, 2026-08-13:
                               // "we dont want to ask for another email for more like
                               // 5 min". This used to be tabletResetMs (90 s), which meant
                               // a conversation longer than a minute and a half re-gated
                               // somebody who had already given their email, and the
                               // operator had to hit the override. Deliberately NOT the
                               // same number as tabletResetMs: the tablet still goes home
                               // to the six tiles after 90 s so the next visitor does not
                               // walk up to somebody else's product card, but the person
                               // standing there is still remembered.
    tabletFollowMs:    60000,  // how recently the tablet must have been touched for it
                               // to auto-open the card when the TV changes film. Past
                               // this, nobody is standing there: the TV plays on and
                               // the tablet stays on the six tiles.
    gateAbandonMs:     45000,  // a gate nobody finished: back to the tiles, so
                               // the next person walks up to six tiles, not a form
    attractHoldMs:     11000   // dwell per attract card
  },

  lead: { url: '/expo-leads.html?staff=1' },   // the EXISTING form. Do not build a second one.

  storageKeyPrefix: 'ssKiosk.v1.',
  logEndpoint: '/log',         // serve.py appends to disk. Absent == silent no-op.
  eventsEndpoint: '/events',   // READING the day back. Same port+1 rule as /log.
  busEndpoint: '/bus'          // serve.py relays taps to a TV on another device.
};

/* Telemetry goes to its own port, one above the page's.

   A browser allows about six connections per HOST. The TV holds a permanent
   event stream plus a live connection per film — the whole budget — so
   telemetry POSTs queued behind the videos and never sent. Measured: fifteen
   films played, fifteen events in the page, zero on disk. A different port is
   a different origin with its own pool, so the record cannot be starved by
   the films. Falls back to same-origin when the port is not knowable. */
CONFIG.altOrigin = '';       // the port+1 origin, '' when it is not knowable

(function () {
  if (typeof location === 'undefined') return;
  if (location.protocol.indexOf('http') !== 0 || !location.port) return;
  var next = parseInt(location.port, 10) + 1;
  if (!isFinite(next)) return;
  CONFIG.altOrigin  = location.protocol + '//' + location.hostname + ':' + next;
  CONFIG.logEndpoint = CONFIG.altOrigin + '/log';
  // READS of the day's record move with the writes. Report.load() used to ask
  // the PAGE port for /events — the one origin whose six connections are spent
  // on films — which is the exact starvation this split was built to end, run
  // backwards. Same listener, same JSON, its own pool.
  CONFIG.eventsEndpoint = CONFIG.altOrigin + '/events';
})();

/* A file that must NOT compete with the six warm product films for the page
   origin's ~6 connections. serve.py listens on port+1 as well, serving the same
   directory with the same Range support, so this is the identical file down a
   pool of its own.

   Measured, and the reason this exists: with the StreamStage services film on
   the page origin as a seventh <video>, its request sat NETWORK_LOADING /
   readyState 0 for nine seconds, and Chrome then ABORTED all six product film
   loads to free a slot for it. Nine seconds of black on the attract loop, and
   the six warm layers — the whole instant-start design, measured at 87ms
   tap-to-frame — cold. Off the page origin, neither happens. */
function altMedia(path) {
  return CONFIG.altOrigin ? CONFIG.altOrigin + '/' + path : path;
}

/* No QR is built here, and there is no function that does.
   Every code on both screens is a pre-baked SVG under qr/, written by
   make-qr.py, which holds the URLs and the ?src=booth-calgary&p=&s= tag
   itself. A booth with no internet cannot render a QR from a CDN, and a
   builder in this file that nothing calls is worse than none: it reads like
   the live path and is not. If a url above changes, re-run make-qr.py. */

function productById(id) {
  for (var i = 0; i < CONFIG.products.length; i++) {
    if (CONFIG.products[i].id === id) return CONFIG.products[i];
  }
  return null;
}

/* =============================================================================
   BUS — shared state between the tablet and the TV.

   THREE transports, all running at once, because the TV might be either a
   second window on the same laptop OR a Fire Stick across the room:

     1. BroadcastChannel  — instant, same device, same browser. Zero latency.
     2. localStorage      — same device, older browsers, belt and braces.
     3. SSE via serve.py  — THE CROSS-DEVICE PATH. This is what makes a Fire
                            Stick (or an iPad, or any browser on the same wifi)
                            work as the TV. GET /bus is a live event stream;
                            POST /bus publishes to every connected screen.

   Every message carries an id and receivers drop duplicates, so a message that
   arrives twice (once locally, once off the wire) is handled once.

   If serve.py dies, transports 1 and 2 keep a same-laptop setup running. If
   the wifi dies, the same is true. Only the Fire Stick setup needs the server,
   and the browser auto-reconnects to it — EventSource retries on its own.
   ========================================================================== */
var Bus = (function () {
  var NAME    = CONFIG.storageKeyPrefix + 'bus';
  var chan    = (typeof BroadcastChannel !== 'undefined') ? new BroadcastChannel(NAME) : null;
  var handlers = [];
  var seen    = [];              // ring buffer of recently handled message ids
  var me      = Math.random().toString(36).slice(2, 8);
  var n       = 0;
  var online  = false;           // is the SSE relay connected?
  var onlineHandlers = [];

  function deliver(msg) {
    if (!msg || typeof msg !== 'object') return;
    if (msg._from === me) return;                 // never handle our own echo
    if (msg._id) {
      if (seen.indexOf(msg._id) !== -1) return;   // already handled by another transport
      seen.push(msg._id);
      if (seen.length > 200) seen.splice(0, 100);
    }
    for (var i = 0; i < handlers.length; i++) {
      try { handlers[i](msg); }
      catch (e) {
        // One bad handler must never stop the booth — but swallowing silently
        // hid a real bug during testing, so it still gets reported.
        if (window.console && console.error) console.error('bus handler failed', e);
      }
    }
  }

  if (chan) chan.onmessage = function (e) { deliver(e.data); };

  window.addEventListener('storage', function (e) {
    if (e.key !== NAME || !e.newValue) return;
    try { deliver(JSON.parse(e.newValue).msg); } catch (err) {}
  });

  /* ---- the cross-device stream ---------------------------------------- */
  function setOnline(v) {
    if (online === v) return;
    online = v;
    for (var i = 0; i < onlineHandlers.length; i++) {
      try { onlineHandlers[i](v); } catch (e) {}
    }
  }

  if (CONFIG.busEndpoint && typeof EventSource !== 'undefined') {
    try {
      var es = new EventSource(CONFIG.busEndpoint);
      es.onopen = function () { setOnline(true); };
      es.onmessage = function (e) {
        setOnline(true);
        try { deliver(JSON.parse(e.data)); } catch (err) {}
      };
      // EventSource reconnects by itself; we only need to reflect the state.
      es.onerror = function () { setOnline(false); };
    } catch (e) { /* file:// or no server — the local transports still work */ }
  }

  return {
    send: function (msg) {
      msg._id   = me + '-' + (++n);
      msg._from = me;

      if (chan) { try { chan.postMessage(msg); } catch (e) {} }
      try { localStorage.setItem(NAME, JSON.stringify({ n: Math.random(), msg: msg })); } catch (e) {}

      if (CONFIG.busEndpoint && typeof fetch !== 'undefined') {
        try {
          fetch(CONFIG.busEndpoint, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(msg),
            keepalive: true
          }).then(function () { setOnline(true); })
            .catch(function () { setOnline(false); });
        } catch (e) {}
      }
    },
    on: function (fn) { handlers.push(fn); },
    // Both screens want to be TOLD when the relay drops, not to poll for it —
    // so onConnection (which also fires immediately with the current value) is
    // the whole surface. There is no isOnline() getter because nothing ever
    // asked one.
    onConnection: function (fn) { onlineHandlers.push(fn); fn(online); }
  };
})();

/* =============================================================================
   TELEMETRY — the only record of two days of floor traffic.

   Rules this obeys:
   - Append-only, written to localStorage the instant the event happens, so a
     tab that dies loses nothing.
   - Each surface writes its OWN key ('tv' / 'tablet'), so two windows can
     never clobber each other's writes.  Export merges and sorts.
   - Best-effort POST to serve.py, which appends a JSONL file on disk so a
     browser-profile wipe is survivable too.  Failure here is not an error.
   - We record QR IMPRESSIONS, not scans.  A scan happens on the attendee's
     phone and is not observable from this page.  Anything labelled "scan"
     in the export would be a lie, so nothing is.
   ========================================================================== */
var Telemetry = (function () {
  var surface = 'unknown';
  var KEY = function () { return CONFIG.storageKeyPrefix + 'events.' + surface; };
  var sessionId = null;
  var seq = 0;

  function nowIso() { return new Date().toISOString(); }

  function read(key) {
    try { return JSON.parse(localStorage.getItem(key) || '[]'); }
    catch (e) { return []; }
  }

  function push(ev) {
    var key = KEY();
    var arr = read(key);
    arr.push(ev);
    try { localStorage.setItem(key, JSON.stringify(arr)); }
    catch (e) {
      // Storage full (two days of events should not get near this, but if it
      // does): drop the OLDEST half rather than lose today's tail.
      try {
        arr = arr.slice(Math.floor(arr.length / 2));
        arr.push(ev);
        localStorage.setItem(key, JSON.stringify(arr));
      } catch (e2) {}
    }
  }

  /* ----------------------------------------------------------------------
     GETTING EVENTS ONTO DISK.

     Not one POST per event. The TV holds a permanent EventSource plus a live
     <video> connection per film — six sockets to one origin, which is exactly
     Chrome's per-host limit, so single-event POSTs queue behind the videos and
     never send. Measured on a TV eight seconds after load: film_start and
     film_first_frame were in its own localStorage and the server had received
     neither. Two days of floor traffic would have quietly stopped reaching the
     disk the moment the films warmed up. sendBeacon did not fix it either.

     So: localStorage stays the source of truth and is written synchronously as
     always, and a flusher posts everything not yet acknowledged as ONE batch
     every few seconds. An event is only marked sent when the server has
     confirmed it, so a stalled request costs nothing — the next flush carries
     the backlog. Far fewer requests, and it self-heals.
     -------------------------------------------------------------------- */
  var flushing = false;

  function flush() {
    if (!CONFIG.logEndpoint || typeof fetch === 'undefined' || flushing) return;
    var key = KEY();
    var arr = read(key);
    var out = [];
    for (var i = 0; i < arr.length; i++) if (!arr[i].sent) out.push(arr[i]);
    if (!out.length) return;

    /* A flush that STALLS must not wedge the flusher. The whole reason this
       is batched is that requests can sit unsent behind the video connections;
       if the in-flight guard never cleared, the first stalled request would
       block every later event for the rest of the day. So each attempt is
       given a deadline and then abandoned — the events stay unsent and the
       next tick tries again. */
    var ctrl = (typeof AbortController !== 'undefined') ? new AbortController() : null;
    var bail = setTimeout(function () {
      flushing = false;
      if (ctrl) { try { ctrl.abort(); } catch (e) {} }
    }, 6000);

    flushing = true;
    fetch(CONFIG.logEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=UTF-8' },  // safelisted: no preflight
      body: JSON.stringify(out),
      signal: ctrl ? ctrl.signal : undefined
    }).then(function (r) {
      clearTimeout(bail);
      flushing = false;
      if (!r.ok) return;                       // leave them unsent; retry next tick
      var ids = {};
      for (var j = 0; j < out.length; j++) ids[out[j].eid] = 1;
      var now = read(key);
      for (var k = 0; k < now.length; k++) if (ids[now[k].eid]) now[k].sent = 1;
      try { localStorage.setItem(key, JSON.stringify(now)); } catch (e) {}
    }).catch(function () { clearTimeout(bail); flushing = false; });
  }

  function flushOnExit() {
    // Last chance as the tab dies. Best effort; localStorage still holds it all.
    if (!CONFIG.logEndpoint) return;
    try {
      var arr = read(KEY()), out = [];
      for (var i = 0; i < arr.length; i++) if (!arr[i].sent) out.push(arr[i]);
      if (!out.length) return;
      if (navigator && typeof navigator.sendBeacon === 'function') {
        navigator.sendBeacon(CONFIG.logEndpoint, new Blob([JSON.stringify(out)], { type: 'text/plain' }));
      }
    } catch (e) {}
  }

  if (typeof window !== 'undefined') {
    setInterval(flush, 3000);
    window.addEventListener('pagehide', flushOnExit);
  }

  return {
    init: function (s) {
      surface = s;
      sessionId = nowIso() + '-' + Math.floor(Math.random() * 1e6).toString(36);
      this.log('surface_open', {});
    },

    /* EVERY event type this booth writes. Kept complete on purpose: this list
       was three types short of the truth for a fortnight, and Report.rollup
       silently ignored the missing ones — including the whole gate, which is
       the one thing the booth was rebuilt to measure.

       If you add a type here, add it to Report.rollup too. A type that is
       written all day and never counted is a number Daniel does not have.

         the visitor    tap · tap_render · surface_open
         the gate       gate_shown · gate_closed · gate_override ·
                        visitor_start · visitor_end · lead_captured · offer_shown
         a film         film_start · film_first_frame · film_progress ·
                        film_complete · film_abandon
         the operator   film_pause · film_resume · film_pause_expired ·
                        order_set · cmd_refused · mute_set · fullscreen_refused
         the TV alone   attract_cycle · services_start · services_complete
         a bad film     film_stalled · film_broken · film_recovered ·
                        film_unavailable
         a code         qr_impression        (an IMPRESSION, never a scan)
         the day        export
       serve.py writes cmd_refused itself, with surface:"server". */
    log: function (type, data) {
      var ev = {
        eid: Date.now().toString(36) + '-' + (seq++).toString(36),
        t: nowIso(),
        ms: Date.now(),
        surface: surface,
        session: sessionId,
        type: type
      };
      for (var k in data) if (Object.prototype.hasOwnProperty.call(data, k)) ev[k] = data[k];
      push(ev);
      flush();
      return ev;
    },

    all: function () {
      var out = [];
      var surfaces = ['tv', 'tablet'];
      for (var i = 0; i < surfaces.length; i++) {
        out = out.concat(read(CONFIG.storageKeyPrefix + 'events.' + surfaces[i]));
      }
      out.sort(function (a, b) { return (a.ms || 0) - (b.ms || 0); });
      return out;
    }
    // There is deliberately no clear(). Nothing called it, and the one record
    // of two days of floor traffic does not need a delete button on it.
  };
})();

/* -----------------------------------------------------------------------------
   QR IMPRESSION TIMER.  Starts when a QR becomes visible, logs one event with
   the number of seconds it was actually on screen when it goes away.  This is
   an impression, and the export says so.
   -------------------------------------------------------------------------- */
function QrImpression(target, surface) {
  this.target = target;         // product id, or 'facebook'
  this.surface = surface;
  this.t0 = null;
}
QrImpression.prototype.start = function () {
  if (this.t0 !== null) return;
  this.t0 = Date.now();
};
QrImpression.prototype.stop = function () {
  if (this.t0 === null) return;
  var secs = (Date.now() - this.t0) / 1000;
  this.t0 = null;
  if (secs < 0.4) return;       // a flicker is not an impression
  Telemetry.log('qr_impression', {
    target: this.target,
    shownSeconds: Math.round(secs * 10) / 10
  });
};

/* =============================================================================
   ROLLUP + EXPORT — what the hidden operator view shows, and what the
   one-click export writes.
   ========================================================================== */
var Report = (function () {

  /* ==========================================================================
     THE ANSWER, IN WORDS.

     Daniel reads this on the flight home, not a spreadsheet. Every line is a
     sentence about something that was counted; a line whose number cannot be
     counted honestly is simply not emitted, so a short list means a quiet day
     and never a broken report.

     The question it exists to answer is the one he asked when the gate went
     in: did putting a form in front of the first film COST me leads or CAPTURE
     them? Both sides of that are stated, in the same paragraph, and no verdict
     is drawn — the two numbers are the verdict.
     ======================================================================== */
  function plural(n, one, many) { return n + ' ' + (n === 1 ? one : many); }

  function plainEnglish(r) {
    var out = [];

    if (!r.gateShown && !r.visitors && !r.taps) {
      out.push('Nothing has happened yet today — no taps, no gate, no films.');
      return out;
    }

    if (!r.gateShown) {
      out.push('The gate was never shown. Either nobody tapped a tile, or the ' +
               'films were already unlocked when they did.');
    } else {
      out.push(plural(r.gateShown, 'person', 'people') + ' met the gate. ' +
               r.gateCompleted + ' typed a studio name and an email and went ' +
               'through — ' + r.gateConversion + '%.');

      if (r.gateWalkedAway) {
        var bits = [];
        if (r.gateAbandoned) bits.push(r.gateAbandoned + ' walked away from the form');
        if (r.gateBacked)    bits.push(r.gateBacked + ' went back to the six tiles');
        out.push(bits.join(' and ') + '. That is ' +
                 plural(r.gateWalkedAway, 'person', 'people') + ' the gate stopped.');
      }

      if (r.gateOverridden) {
        out.push(plural(r.gateOverridden, 'visitor was', 'visitors were') +
                 ' waved through by hand. They watched the films; you got no email.');
      }

      // The whole point, stated as two facts side by side.
      out.push('So: the gate CAPTURED ' + plural(r.gateCompleted, 'email', 'emails') +
               ' with a studio name attached, and it COST ' +
               plural(r.gateUnfinished, 'person', 'people') +
               ' who saw the form and did not finish it.');
    }

    if (r.leads) {
      out.push(plural(r.leads, 'email was', 'emails were') + ' captured in total, ' +
               'counting the gate and anything typed after a film.');
    }

    if (r.visitors) {
      out.push(plural(r.visitors, 'visitor', 'visitors') + ' got through to the films' +
               (r.tapsPerVisitor !== null ? ', ' + r.tapsPerVisitor + ' taps each' : '') +
               (r.filmsPerVisitor !== null ? ' and ' + r.filmsPerVisitor + ' films each' : '') +
               '.');
    }

    if (r.starts) {
      out.push(r.starts + ' films started, ' + r.completes + ' watched to the end — ' +
               r.completionRate + '%.');
    }

    if (r.servicesStarts) {
      out.push('The StreamStage recital film ran ' + plural(r.servicesStarts, 'time', 'times') +
               ', ' + r.servicesCompletes + ' of them to the end.');
    }

    if (r.stalls || r.filmsUnavailable) {
      var bad = [];
      if (r.stalls) bad.push(plural(r.stalls, 'film', 'films') + ' stalled mid-play');
      if (r.filmsUnavailable) {
        bad.push(plural(r.filmsUnavailable, 'tap', 'taps') +
                 ' got the scan card because the film could not play');
      }
      out.push(bad.join(', and ') + '. Check the media files before the next day.');
    }
    if (r.fullscreenRefusals) {
      out.push('The TV refused a fullscreen request ' +
               plural(r.fullscreenRefusals, 'time', 'times') +
               ' — a browser will not go fullscreen without somebody touching it. ' +
               'Do it once on the TV itself.');
    }
    if (r.pauseExpiries) {
      out.push(plural(r.pauseExpiries, 'film was', 'films were') +
               ' left paused long enough that the TV went back to the attract loop on its own.');
    }
    if (r.refusals) {
      out.push(plural(r.refusals, 'command was', 'commands were') +
               ' refused for not coming from the phone. If that number is climbing, ' +
               'something is publishing without src:"phone".');
    }

    return out;
  }

  function rollup(events) {
    var per = {};        // product id -> counters
    var r = {
      taps: 0, starts: 0, completes: 0, abandons: 0,
      attractCycles: 0, leads: 0, offersShown: 0,
      fbImpressions: 0, fbSeconds: 0,
      firstEvent: null, lastEvent: null,

      /* ------------------------------------------------------------------
         THE GATE. The only question this booth was rebuilt to answer, and
         until now the only one it could not: asking for a studio name and an
         email before the first film — did that cost leads, or capture them?

         Every figure here is COUNTED off an event that was written at the
         moment it happened. None of it is inferred, and where a number cannot
         be counted honestly it is not reported at all.

           gateShown       gate_shown      met the form
           gateCompleted   visitor_start captured:true — typed both boxes
           gateOverridden  gate_override   waved through by hand
           gateAbandoned   gate_closed reason:"abandoned" — walked off mid-form
           gateBacked      gate_closed reason:"back" — chose the tiles instead
         ------------------------------------------------------------------ */
      gateShown: 0, gateCompleted: 0, gateOverridden: 0,
      gateAbandoned: 0, gateBacked: 0, gateClosedOther: 0,

      /* A VISITOR is one person's session at the tablet: it opens on the first
         unlock and closes when they walk away (or the operator's override
         opens it without a capture). visitors is how many people got through
         to a film at all — captured or waved through. */
      visitors: 0, visitorsCaptured: 0, visitorsEnded: 0,

      /* StreamStage's own recital film, which only the attract loop and the
         operator's phone ever start. Counted apart from the six products
         because it is not one, and mixing it in would flatter the products. */
      servicesStarts: 0, servicesCompletes: 0,

      /* The operator's own hands, and the wire refusing something. */
      pauses: 0, resumes: 0, pauseExpiries: 0, ordersSet: 0, refusals: 0,
      mutes: 0, fullscreenRefusals: 0,

      /* A film that could not play, which is not the same as a film nobody
         wanted. stalls is the watchdog firing; filmsUnavailable is a visitor
         tapping a tile and getting the scan card instead of a film. */
      stalls: 0, filmsBroken: 0, filmsRecovered: 0, filmsUnavailable: 0,

      /* Housekeeping, so nothing written is left uncounted. */
      surfaceOpens: 0, exports: 0,

      per: per
    };

    var tapLat = [];     // tablet tap -> tablet repaint, which is NOT the TV's

    function bucket(id) {
      if (!per[id]) per[id] = {
        id: id, name: (productById(id) || {}).name || id,
        taps: 0, starts: 0, completes: 0, abandons: 0,
        watchedSeconds: 0, qrImpressions: 0, qrSeconds: 0
      };
      return per[id];
    }
    for (var i = 0; i < CONFIG.products.length; i++) bucket(CONFIG.products[i].id);

    /* Watch time is walked as a sequence of VIEWS rather than summed off the
       closing event, because a view can end three ways and one of them is
       "the tab died". A view opened by film_start stays open, absorbing
       film_progress marks, until it is closed by a complete or an abandon.
       Anything still open at the end of the log is a crash: it commits the
       last progress mark we saw, so a lost view still contributes the
       seconds it genuinely got. */
    var open = {};              // surface -> {product, watched}
    var lat = [];               // tap -> first painted frame, per play

    function commit(view) {
      if (!view) return;
      bucket(view.product).watchedSeconds += (view.watched || 0);
    }

    for (var j = 0; j < events.length; j++) {
      var e = events[j];
      if (r.firstEvent === null) r.firstEvent = e.t;
      r.lastEvent = e.t;
      var s = e.surface || 'tv';

      if (e.type === 'tap') { r.taps++; bucket(e.product).taps++; }

      else if (e.type === 'film_start') {
        commit(open[s]);                       // an unclosed previous view = crash
        open[s] = { product: e.product, watched: 0 };
        r.starts++; bucket(e.product).starts++;
      }

      else if (e.type === 'film_progress') {
        if (open[s] && open[s].product === e.product) {
          open[s].watched = Math.max(open[s].watched, e.watchedSeconds || 0);
        }
      }

      else if (e.type === 'film_complete') {
        r.completes++;
        var bc = bucket(e.product); bc.completes++;
        bc.watchedSeconds += (e.watchedSeconds || 0);
        open[s] = null;
      }

      else if (e.type === 'film_abandon') {
        r.abandons++;
        var ba = bucket(e.product); ba.abandons++;
        // Real seconds watched; older events only carried the stop position.
        ba.watchedSeconds += (e.watchedSeconds !== undefined ? e.watchedSeconds : (e.atSecond || 0));
        open[s] = null;
      }

      else if (e.type === 'film_first_frame') {
        if (typeof e.latencyMs === 'number') {
          lat.push(e.latencyMs);
          var bl = bucket(e.product);
          bl.latencySamples = (bl.latencySamples || 0) + 1;
          bl.latencyTotal = (bl.latencyTotal || 0) + e.latencyMs;
        }
      }

      else if (e.type === 'attract_cycle') { r.attractCycles++; }
      else if (e.type === 'offer_shown')   { r.offersShown++; }
      else if (e.type === 'lead_captured') { r.leads++; }

      /* ---- the gate, start to finish ---------------------------------- */
      else if (e.type === 'gate_shown')    { r.gateShown++; }
      else if (e.type === 'gate_override') { r.gateOverridden++; }
      else if (e.type === 'gate_closed') {
        // A gate that CLOSED because it was submitted does not log this at
        // all — closeGate() is called without a reason on the success path —
        // so every one of these is somebody who did not finish.
        if (e.reason === 'abandoned')  r.gateAbandoned++;
        else if (e.reason === 'back')  r.gateBacked++;
        else                           r.gateClosedOther++;
      }
      else if (e.type === 'visitor_start') {
        r.visitors++;
        // captured:true has exactly ONE source — the gate form's submit
        // handler, which is the only caller of Visitor.start() that passes an
        // email. The operator override passes null. So a captured visitor IS
        // a finished gate, and this is a count, not an inference.
        if (e.captured) { r.visitorsCaptured++; r.gateCompleted++; }
      }
      else if (e.type === 'visitor_end')   { r.visitorsEnded++; }

      /* ---- the TV on its own ------------------------------------------ */
      else if (e.type === 'services_start')    { r.servicesStarts++; }
      else if (e.type === 'services_complete') { r.servicesCompletes++; }
      /* ---- a film that would not play --------------------------------- */
      else if (e.type === 'film_stalled')     { r.stalls++; }
      else if (e.type === 'film_broken')      { r.filmsBroken++; }
      else if (e.type === 'film_recovered')   { r.filmsRecovered++; }
      else if (e.type === 'film_unavailable') {
        r.filmsUnavailable++;
        // A tap that got the scan card instead of a film. Counted against the
        // product, because "nobody watched CostumeCraft" and "CostumeCraft
        // could not play" are very different findings.
        if (e.product) bucket(e.product).unavailable = (bucket(e.product).unavailable || 0) + 1;
      }
      else if (e.type === 'mute_set')           { if (e.muted) r.mutes++; }
      else if (e.type === 'fullscreen_refused') { r.fullscreenRefusals++; }

      /* ---- the operator's hands --------------------------------------- */
      else if (e.type === 'film_pause')         { r.pauses++; }
      else if (e.type === 'film_resume')        { r.resumes++; }
      else if (e.type === 'film_pause_expired') { r.pauseExpiries++; }
      else if (e.type === 'order_set')          { r.ordersSet++; }
      else if (e.type === 'cmd_refused')        { r.refusals++; }

      /* ---- housekeeping ------------------------------------------------ */
      else if (e.type === 'surface_open') { r.surfaceOpens++; }
      else if (e.type === 'export')       { r.exports++; }

      else if (e.type === 'tap_render') {
        if (typeof e.latencyMs === 'number') tapLat.push(e.latencyMs);
      }

      else if (e.type === 'qr_impression') {
        if (e.target === 'facebook') {
          r.fbImpressions++; r.fbSeconds += (e.shownSeconds || 0);
        } else {
          var bq = bucket(e.target); bq.qrImpressions++; bq.qrSeconds += (e.shownSeconds || 0);
        }
      }
    }
    for (var sk in open) if (Object.prototype.hasOwnProperty.call(open, sk)) commit(open[sk]);

    lat.sort(function (a, b) { return a - b; });
    r.startLatency = lat.length ? {
      samples: lat.length,
      medianMs: lat[Math.floor(lat.length / 2)],
      worstMs:  lat[lat.length - 1]
    } : null;

    r.completionRate = r.starts ? Math.round((r.completes / r.starts) * 100) : 0;

    // The TABLET's tap-to-repaint. A different number from startLatency above,
    // which is the TV's tap-to-first-painted-frame. Two screens, two clocks;
    // reported separately because averaging them would mean nothing.
    tapLat.sort(function (a, b) { return a - b; });
    r.tapLatency = tapLat.length ? {
      samples: tapLat.length,
      medianMs: tapLat[Math.floor(tapLat.length / 2)],
      worstMs:  tapLat[tapLat.length - 1]
    } : null;

    /* ------------------------------------------------------------------
       THE THREE NUMBERS THE GATE IS JUDGED ON.

       null, not 0, when there is nothing to divide by: a booth that has not
       opened yet has no conversion rate, and printing "0%" would read as a
       failure rather than as an empty morning.
       ------------------------------------------------------------------ */
    r.gateConversion  = r.gateShown ? Math.round((r.gateCompleted / r.gateShown) * 100) : null;
    r.gateUnfinished  = Math.max(0, r.gateShown - r.gateCompleted - r.gateOverridden);
    r.gateWalkedAway  = r.gateAbandoned + r.gateBacked;
    r.tapsPerVisitor  = r.visitors ? Math.round((r.taps / r.visitors) * 10) / 10 : null;
    r.filmsPerVisitor = r.visitors ? Math.round((r.starts / r.visitors) * 10) / 10 : null;
    r.plain = plainEnglish(r);

    // Most-watched == most seconds of film actually consumed, not most taps.
    var best = null;
    for (var id in per) {
      if (!Object.prototype.hasOwnProperty.call(per, id)) continue;
      if (!best || per[id].watchedSeconds > best.watchedSeconds) best = per[id];
    }
    r.mostWatched = (best && best.watchedSeconds > 0) ? best : null;

    r.ranked = CONFIG.products.map(function (p) { return per[p.id]; })
      .sort(function (a, b) { return b.taps - a.taps || b.watchedSeconds - a.watchedSeconds; });

    return r;
  }

  function toCsv(events) {
    var cols = ['t', 'surface', 'type', 'product', 'target', 'atSecond',
                'watchedSeconds', 'durationSeconds', 'shownSeconds', 'percent',
                'latencyMs', 'via', 'session'];
    var lines = [cols.join(',')];
    for (var i = 0; i < events.length; i++) {
      var e = events[i], row = [];
      for (var c = 0; c < cols.length; c++) {
        var v = e[cols[c]];
        v = (v === undefined || v === null) ? '' : String(v);
        row.push(/[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v);
      }
      lines.push(row.join(','));
    }
    return lines.join('\n');
  }

  function download(filename, text, mime) {
    var blob = new Blob([text], { type: mime + ';charset=utf-8' });
    var a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(function () { URL.revokeObjectURL(a.href); a.remove(); }, 1500);
  }

  function stamp() {
    var d = new Date(), p = function (n) { return (n < 10 ? '0' : '') + n; };
    return d.getFullYear() + p(d.getMonth() + 1) + p(d.getDate()) + '-' + p(d.getHours()) + p(d.getMinutes());
  }

  /* --------------------------------------------------------------------
     THE WHOLE RECORD, not just this browser's half.

     When the TV is a Fire Stick it is a different DEVICE, so its events are
     in its own localStorage and this page can never see them. Both screens
     POST every event to serve.py though, so the server holds the only
     complete record — ask it first, and fall back to local storage when
     there is no server (or it is unreachable).

     Local events are merged on top rather than replaced: if the relay was
     down for a stretch, this browser still holds events the server missed.
     ------------------------------------------------------------------- */
  function key(e) {
    return [e.t, e.surface, e.type, e.product || '', e.target || ''].join('|');
  }

  /* TWO things were wrong with this and both had the same cause.

     It fetched a RELATIVE '/events', which is the PAGE port — the origin whose
     ~6 connections are spent on the film layers, and the exact starvation the
     telemetry split was built to end (measured: 15 films played, 0 events on
     disk). Reading the day back down that pipe was that bug, run backwards.

     And it had no deadline. The operator sheet re-renders every 3 seconds, so
     a request that never settles on a dead or half-dead server left the tally
     stuck on whatever it last painted, with no way to tell that from a quiet
     booth. Now it is given 6 seconds — the same deadline the flusher uses —
     and then falls back to what this browser holds, which is never nothing. */
  var LOAD_DEADLINE_MS = 6000;

  /* load()          — TODAY, which is what the tally on screen means.
     load({all:true}) — every day on disk, which is what an export means.

     The server's /events used to return everything ever recorded, and the two
     Android clients read it behind a hard 512KB cap — about 2,648 events, or
     roughly the middle of day two. Past that the read stops mid-byte, the
     parse throws, and the only remote-control channel to a tablet nobody can
     reach over adb dies silently. So the default is one day, and the caller
     that genuinely wants both says so. */
  function load(opts) {
    var local = Telemetry.all();
    if (typeof fetch === 'undefined') return Promise.resolve(local);

    // cap=off is for a BROWSER only. The server caps /events at 320KB by
    // default because the two Android clients read it behind a hard 512KB
    // buffer and a reply over that is a truncated array that throws — measured
    // at 14MB on the live booth, which had already killed the phone's command
    // channel. A browser has no such limit, and an export genuinely wants the
    // whole show, so this one caller opts out. Nothing on Android may.
    var url = CONFIG.eventsEndpoint || '/events';
    if (opts && opts.all) url += '?day=all&cap=off';

    var ctrl = (typeof AbortController !== 'undefined') ? new AbortController() : null;
    var bail = setTimeout(function () {
      if (ctrl) { try { ctrl.abort(); } catch (e) {} }
    }, LOAD_DEADLINE_MS);

    return fetch(url, {
      cache: 'no-store',
      signal: ctrl ? ctrl.signal : undefined
    })
      .then(function (r) { clearTimeout(bail); return r.ok ? r.json() : []; })
      .then(function (server) {
        if (!server || !server.length) return local;
        var seen = {}, out = [];
        server.concat(local).forEach(function (e) {
          var k = key(e);
          if (seen[k]) return;
          seen[k] = 1;
          out.push(e);
        });
        out.sort(function (a, b) { return (a.ms || 0) - (b.ms || 0); });
        return out;
      })
      .catch(function () { clearTimeout(bail); return local; });
  }

  return {
    rollup: rollup,
    load: load,
    exportAll: function (events) {
      events = events || Telemetry.all();
      var r = rollup(events);
      Telemetry.log('export', { events: events.length });
      download('booth-calgary-' + stamp() + '.csv', toCsv(events), 'text/csv');
      setTimeout(function () {
        download('booth-calgary-' + stamp() + '.json', JSON.stringify({
          exportedAt: new Date().toISOString(),
          // First key in the file on purpose: the day in sentences, before the
          // spreadsheet. Same lines the operator sheet shows.
          theDay: r.plain,
          note: 'qr_impression counts times a QR was ON SCREEN and for how long. ' +
                'It is NOT a scan count — a scan happens on the attendee phone and ' +
                'cannot be observed from this page. Real scans are attributable on ' +
                'the destination side via ?src=booth-calgary&p=<product>&s=<screen>.',
          summary: r,
          events: events
        }, null, 2), 'application/json');
      }, 400);
      return r;
    }
  };
})();
